name: deploy container

on:
    push:
        branches: [main, develop]
        paths-ignore:
            - "README.md"

jobs:
    build:
        runs-on: ubuntu-22.04
        name: Build
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm run build
